apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"
          limits:
            memory: "150Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
