apiVersion: v1
kind: LimitRange
metadata: 
  name: limit-container
spec:
  limits:
    - max:
        cpu: "50m"
        memory: "100Mi"
      min: 
        cpu: "20m" 
        memory: "20Mi"
      default:
        cpu: "40m"
        memory: "40Mi"
      defaultRequest:
        cpu: "20m"
        memory: "25Mi"
      type: Container
